name: Docker
on: [ push, pull_request ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether to push to DockerHub, and set tag
      if: |
        github.event_name == 'push' &&
        ( startsWith( github.ref, 'refs/tags/' ) ||
          contains( fromJSON('["master","develop","testnet","hardfork"]'), github.ref_name ) )
      run: |
        if [ "${GITHUB_REF_NAME}" == "master" ] ; then
          DOCKER_PUSH_TAG=latest
        else
          DOCKER_PUSH_TAG=${GITHUB_REF_NAME}
        fi
        echo "DOCKER_PUSH_TAG=${DOCKER_PUSH_TAG}"
        echo "DOCKER_PUSH_TAG=${DOCKER_PUSH_TAG}" >> $GITHUB_ENV
    - name: Test tag
      if: env.DOCKER_PUSH_TAG != ''
      run: echo "${DOCKER_PUSH_TAG}"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build only
      uses: docker/build-push-action@v3
      with:
        context: .
        load: true
    - name: Login to DockerHub
      if: env.DOCKER_PUSH_TAG != ''
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to DockerHub
      if: env.DOCKER_PUSH_TAG != ''
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_REPO_PATH }}:${{ env.DOCKER_PUSH_TAG }}
